apiVersion: v2
name: vcverifier
description: Chart holder for argo-cd

type: application
version: 1.0.4
appVersion: "1.0.0"

dependencies:
  - name: vcverifier
    version: 1.0.4
    repository: https://i4Trust.github.io/helm-charts
