vcverifier:
  deployment:
    image:
      repository: quay.io/fiware/vcverifier
      tag: 2.0.1
      #tag: 0.0.3-pre-3
      #pullPolicy: Always
      pullPolicy: IfNotPresent
    logging: 
      level: DEBUG
      pathsToSkip: 
        - "/health"
        - "/metrics"
    ssikit:
      auditorUrl: http://provider-waltid-vcwaltid:7003
    verifier:
      tirAddress: https://satellite.i4trust.fiware.dev/trusted_issuer/v3/issuers/
      did: did:key:z6MksU6tMfbaDzvaRe5oFE4eZTVTV4HJM4fmQWWGsDGQVsEr
    configRepo:
      configEndpoint: http://pdc-ccs-credentials-config-service:8080/
    
  route:
    enabled: true
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge

issuerKey:
  initEnabled: true
  waltCoreUrl: http://provider-waltid-vcwaltid:7000
  kty: "OKP"
  d: "WgcX0y0OZxlA6FtLk6m3lwy_sZMvKazVax9ER10T7xY"
  use: "sig"
  crv: "Ed25519"
  kid: "z6MksU6tMfbaDzvaRe5oFE4eZTVTV4HJM4fmQWWGsDGQVsEr"
  x: "vkT4YIYHjl-n2C_ijH_TH6iMMk527WulaXX85yDM6Pg"
  alg: "EdDSA"
