vcverifier:
  deployment:
    image:
      tag: 0.0.3-pre-3
      pullPolicy: Always
    protectedResource: https://provider-kong-kong-i4t-provider-main.apps.fiware.fiware.dev/orion-vc/ngsi-ld/v1
    tirAddress: https://satellite.i4trust.fiware.dev/trusted_issuer/v3/issuers/
    #did: did:key:abc
    walt:
      coreUrl: http://provider-waltid-vcwaltid:7000
      signatoryUrl: http://provider-waltid-vcwaltid:7001
      auditorUrl: http://provider-waltid-vcwaltid:7003
      custodianUrl: http://provider-waltid-vcwaltid:7002
      essifUrl: http://provider-waltid-vcwaltid:7004
  route:
    enabled: true
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
