apiVersion: v1
kind: ConfigMap
metadata:
  name: provider-ccs-data-cm
data:
  service_pds.json: |
    {
      "id": {{ .Values.service.idPDS | quote }},
      "credentials": [
        {
          "type": "VerifiableCredential",
          "trustedParticipantsLists": [
            {{ .Values.service.trustedParticipantsLists | quote }}
          ],
          "trustedIssuersLists": [
            {{ .Values.service.trustedIssuersLists | quote }}
          ]
        },
        {
          "type": "PacketDeliveryService",
          "trustedParticipantsLists": [
            {{ .Values.service.trustedParticipantsLists | quote }}
          ],
          "trustedIssuersLists": [
            {{ .Values.service.trustedIssuersLists | quote }}
          ]
        }
      ]
    }

  service_as.json: |
    {
      "id": {{ .Values.service.idAS | quote }},
      "credentials": [
        {
          "type": "VerifiableCredential",
          "trustedParticipantsLists": [
            {{ .Values.service.trustedParticipantsLists | quote }}
          ],
          "trustedIssuersLists": [
            {{ .Values.service.trustedIssuersLists | quote }}
          ]
        },
        {
          "type": "ActivationService",
          "trustedParticipantsLists": [
            {{ .Values.service.trustedParticipantsLists | quote }}
          ],
          "trustedIssuersLists": [
            {{ .Values.service.trustedIssuersLists | quote }}
          ]
        }
      ]
    }
