{{- if .Values.service.createServiceConfig -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: provider-ccs-data-{{ randAlphaNum 5 | lower }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "1"
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: provider-ccs-init-data
          image: alpine/curl
          command: 
            - sh
            - -c
            - |
              curl -X POST ${CCS_HOST}/service --header "Content-Type: application/json" -d @/data/service.json
          volumeMounts:
            - name: provider-ccs-init-data-volume
              mountPath: "/data"
              readOnly: true
          env:
            - name: CCS_HOST
              value: {{ .Values.service.ccsHost | quote }}
      volumes:
        - name: provider-ccs-init-data-volume
          projected:
            sources:
              - configMap:
                  name: provider-ccs-data-cm
{{- end }}
