{{- if .Values.issuerKey.initEnabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: provider-verifier-data-{{ randAlphaNum 5 | lower }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: provider-verifier-init-data
          image: alpine/curl
          command: 
            - sh
            - -c
            - |
              curl -X POST ${WALTID_HOST}/v1/key/import -H "Content-Type: application/json" -d '{"kty": {{ .Values.issuerKey.kty | quote }}, "d": {{ .Values.issuerKey.d | quote }}, "use": {{ .Values.issuerKey.use | quote }}, "crv": {{ .Values.issuerKey.crv | quote }}, "kid": {{ .Values.issuerKey.kid | quote }}, "x": {{ .Values.issuerKey.x | quote }}, "alg": {{ .Values.issuerKey.alg | quote }} }' &&
              curl -X POST ${WALTID_HOST}/v1/did/import?keyId={{ .Values.issuerKey.kid }} --data {{ .Values.vcverifier.deployment.verifier.did | quote }}
          env:
            - name: WALTID_HOST
              value: {{ .Values.issuerKey.waltCoreUrl | quote }}
{{- end }}
