credentials-config-service:
  deployment:
    image:
      #repository: quay.io/fiware/credentials-config-service
      repository: quay.io/wi_stefan/credentials-config-service
      tag: 0.0.1-PRE-1

  route:
    enabled: false

  prometheus:
    enabled: false

  database:
    persistence: false
