credentials-config-service:
  deployment:
    image:
      repository: quay.io/fiware/credentials-config-service
      tag: 0.0.1

  route:
    enabled: false

  prometheus:
    enabled: false

  database:
    persistence: false

service:
  createServiceConfig: true
  ccsHost: "http://pdc-ccs-credentials-config-service:8080"
  id: packet-delivery-service
  credentials:
    - type: VerifiableCredential
      trustedParticipantsLists:
        - "https://tir-pdc.gaia-x.fiware.dev"
      trustedIssuersLists:
        - "http://pdc-til-trusted-issuers-list:8080"
    - type: PacketDeliveryService
      trustedParticipantsLists:
        - "https://tir-pdc.gaia-x.fiware.dev"
      trustedIssuersLists:
        - "http://pdc-til-trusted-issuers-list:8080"
        
