credentials-config-service:
  deployment:
    image:
      repository: quay.io/fiware/credentials-config-service
      tag: 0.0.1

  route:
    enabled: false

  prometheus:
    enabled: false

  database:
    persistence: false
