orion:
  broker:
    db:
      hosts:
        - mongodb
      name: orion_ngsi
      auth:
        user: root
        password: dbPassword

  mongo:
    # we want to use the individually deployed mongodb
    enabled: false

  deployment:
    replicaCount: 1

# Enable initial loading of data from configmap
initData:
  initEnabled: true
  orionHost: provider-orion.i4t-provider-main.svc.cluster.local:1026
    
