apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.kong.dblessConfig.configMap }}
data:
  kong.yml: |
    _format_version: "2.1"
    _transform: true
    services:
      - host: {{ .Values.orion.host | quote }}
        name: vc-{{ .Values.orion.name | quote }}
        port: 1026
        protocol: http
        routes:
          - name: pdc-vc
            paths:
              - {{ .Values.orion.pathVc }}
            strip_path: true
        plugins:
          - name: pep-plugin
            config:
              pathprefix: {{ .Values.orion.pathVc | quote }}
              authorizationendpointtype: ExtAuthz
              authorizationendpointaddress: {{ .Values.pdp.authorizationendpointaddress }}
                
          - name: request-transformer
            config:
              remove:
                headers:
                  - Authorization
                  - authorization
                  
      - host: {{ .Values.orion.host | quote }}
        name: {{ .Values.orion.name | quote }}
        port: 1026
        protocol: http
        routes:
          - name: pdc
            paths:
              - {{ .Values.orion.path }}
            strip_path: true
        plugins:
          - name: ngsi-ishare-policies
            config:
              access_token:
                header_names:
                  - "authorization"
                  - "Authorization"
              ar:
                identifier: {{ .Values.ar.identifier | quote }}
                host: {{ .Values.ar.host }}
                token_endpoint: "{{ .Values.ar.host }}/oauth2/token"
                delegation_endpoint: "{{ .Values.ar.host }}/ar/delegation"
              satellite:
                identifier: {{ .Values.satellite.identifier | quote }}
                host: "{{ .Values.satellite.host }}"
                token_endpoint: "{{ .Values.satellite.host }}/token"
                trusted_list_endpoint: "{{ .Values.satellite.host }}/trusted_list"
              jws:
                identifier: {{ .Values.jws.identifier | quote }}
                private_key: |
                  {{ .Values.jws.private_key | nindent 18 }}
                x5c: |
                  {{ .Values.jws.x5c | nindent 18 }}
              
          - name: request-transformer
            config:
              remove:
                headers:
                  - Authorization
                  - authorization
