apiVersion: v2
name: trusted-issuers-list
description: Chart holder for argo-cd

type: application
version: 0.0.5
appVersion: "0.0.1"

dependencies:
  - name: trusted-issuers-list
    version: 0.0.3
    repository: https://fiware.github.io/helm-charts
