trusted-issuers-list:
  deployment:
    image:
      repository: quay.io/fiware/trusted-issuers-list
      tag: 0.0.3

  route:
    til:
      enabled: false
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      
  prometheus:
    enabled: false

  database:
    persistence: false

initData:
  tilHost: "http://pdc-til-trusted-issuers-list:8080"
  marketplaceCreateIssuer:
    initEnabled: true
    did: "did:key:z6MkvdQnXeKgRceAhNsZYjpQjSFcmTXshyGDvnNw7gziQhjG"
    
