## values to be used for deployement in PoC namespaces
## additional config file is used, since we rely on managed databases there.

source: https://github.com/FIWARE-Ops/i4trust-provider
release: i4t-provider-demo
destination_namespace: &destination i4t-provider-demo
purpose: &purpose i4trust-provider-env
branch: &branch main
secretsEnabled: &secretsEnabled false

applications:
  - name: mongodb
    enabled: true
    source_path: applications/mongodb
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml

  - name: mysql
    enabled: true
    source_path: applications/mysql
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml

  - name: ishare-satellite
    enabled: true
    source_path: applications/satellite
    source_ref: main
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: provider-orion
    enabled: true
    source_path: applications/provider-orion
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml
    values:
      orion:
        broker:
          db:
            hosts:
              - mongodb.i4t-provider-main.svc.cluster.local
      initData:
        orionHost: provider-orion.i4t-provider-main.svc.cluster.local:1026

  - name: provider-kong
    enabled: true
    source_path: applications/provider-kong
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml
    values:
      ar:
        host: "https://provider-keyrock-0-i4t-provider-main.apps.fiware.fiware.dev"
      satellite:
        # Need to specify valid satellite hostname here
        host: "https://ishare-satellite-i4t-provider-main.apps.fiware.fiware.dev"

  - name: provider-keyrock
    enabled: true
    source_path: applications/provider-keyrock
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml
    values:
      keyrock:
        host: https://provider-keyrock-0-i4t-provider-main.apps.fiware.fiware.dev
        satellite:
          # Need to specify valid satellite hostname here
          url: "https://ishare-satellite-i4t-provider-main.apps.fiware.fiware.dev"
          tokenEndpoint: "https://ishare-satellite-i4t-provider-main.apps.fiware.fiware.dev/token"
          partiesEndpoint: "https://ishare-satellite-i4t-provider-main.apps.fiware.fiware.dev/parties"

  - name: provider-as
    enabled: true
    source_path: applications/provider-as
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml
    values:
      activation-service:
        config:
          ar:
            token: "https://provider-keyrock-0-i4t-provider-main.apps.fiware.fiware.dev/oauth2/token"
            policy: "https://provider-keyrock-0-i4t-provider-main.apps.fiware.fiware.dev/ar/policy"
            delegation: "https://provider-keyrock-0-i4t-provider-main.apps.fiware.fiware.dev/ar/delegation"

  - name: provider-portal
    enabled: true
    source_path: applications/provider-portal
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml
    values:
      pdc-portal:
        config:
          external:
            host: https://provider-portal-i4t-provider-main.apps.fiware.fiware.dev
          cb:
            endpoint: "https://provider-kong-kong-i4t-provider-main.apps.fiware.fiware.dev/packetdelivery/ngsi-ld/v1"
            endpoint_siop: "https://provider-kong-kong-i4t-provider-main.apps.fiware.fiware.dev/packetdelivery-vc/ngsi-ld/v1"
          siop:
            #redirect_uri: https://provider-verifier-vcverifier-i4t-provider-main.apps.fiware.fiware.dev/verifier/api/v1/authenticationresponse
            verifier_uri: https://provider-verifier-vcverifier-i4t-provider-main.apps.fiware.fiware.dev
          idp: []
            #- name: "Happy Pets Inc."
            #  id: "EU.EORI.DECONSUMERONE"
            #  url: "https://consumer-keyrock-0-i4t-provider-main.apps.fiware.fiware.dev"
            #  authorize_endpoint: "https://consumer-keyrock-0-i4t-provider-main.apps.fiware.fiware.dev/oauth2/authorize"
            #  token_endpoint: "https://consumer-keyrock-0-i4t-provider-main.apps.fiware.fiware.dev/oauth2/token"

  - name: provider-waltid
    enabled: true
    source_path: applications/provider-waltid
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml

  - name: provider-verifier
    enabled: true
    source_path: applications/provider-verifier
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml
    values:
      vcverifier:
        deployment:
          verifier:
            tirAddress: https://ishare-satellite-i4t-provider-main.apps.fiware.fiware.dev/trusted_issuer/v3/issuers/
          #protectedResource: https://provider-kong-kong-i4t-provider-main.apps.fiware.fiware.dev/orion-vc/ngsi-ld/v1
          

  - name: provider-dsba-pdp
    enabled: true
    source_path: applications/provider-dsba-pdp
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml
    values:
      dsba-pdp:
        deployment:
          ishare:
            ar:
              url: "https://provider-keyrock-0-i4t-provider-main.apps.fiware.fiware.dev"
            trustAnchor:
              url: "https://ishare-satellite-i4t-provider-main.apps.fiware.fiware.dev"
          trustedVerifiers:
            - https://provider-verifier-vcverifier-i4t-provider-main.apps.fiware.fiware.dev/.well-known/jwks

  - name: provider-ccs
    enabled: true
    source_path: applications/provider-ccs
    source_ref: *branch
    destination: *destination
    purpose: *purpose
    helm_values:
    - values.yaml
